### ISSUE TITLE
sabarivka still running if code-coverage is disabled

### ISSUE THREAD

**Issue by cyfer1313** [kopach/karma-sabarivka-reporter#203]
I currently am running Angular 10 with sabarivka 3.2.3 and the latest versions of Karma. When code coverage is enabled, it works great. If in the cli, I run 'ng test --code-coverage=false', I get the following error:

`25 08 2020 09:55:51.271:ERROR [karma-server]: UncaughtException:: Cannot read property 'C:\Apps\Manage\src\polyfills.ts' of undefined
25 08 2020 09:55:51.466:ERROR [karma-server]: TypeError: Cannot read property 'C:\Apps\Manage\src\polyfills.ts' of undefined
    at C:\Apps\Manage\node_modules\karma-sabarivka-reporter\dist\instrumenter.js:30:22
    at Array.forEach (<anonymous>)
    at addFileListToCoverageData (C:\Apps\Manage\node_modules\karma-sabarivka-reporter\dist\instrumenter.js:28:18)
    at exports.sabarivkaReporter.Object.defineProperty.value.onBrowserComplete (C:\Apps\Manage\node_modules\karma-sabarivka-reporter\dist\instrumenter.js:17:9)
    at Server.<anonymous> (C:\Apps\Manage\node_modules\karma\lib\events.js:40:26)
    at Server.emit (events.js:203:15)
    at Browser.onComplete (C:\Apps\Manage\node_modules\karma\lib\browser.js:91:20)
    at Socket.socket.on (C:\Apps\Manage\node_modules\karma\lib\browser.js:207:44)
    at Socket.emit (events.js:203:15)
    at C:\Apps\Manage\node_modules\socket.io\lib\socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)`

The reason we tried this is that we noticed when you go into debug mode for a page, you can't place breakpoints within an observable while code-coverage / sabarivka is enabled. When we disable both, we can place breakpoints inside and observable. Ideally, Sabarivka should only run if code-coverage=true, right?

`        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine', '@angular-devkit/build-angular'],
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-sabarivka-reporter'),
            require('karma-coverage-istanbul-reporter'),
            require('@angular-devkit/build-angular/plugins/karma')
        ],

        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        coverageIstanbulReporter: {
            dir: './coverage/ng-unit-test-app',
            reports: ['html', 'lcovonly', 'text-summary'],
            fixWebpackSourcePaths: true,
            thresholds: {
                global: {
                    statements: 60,
                    lines: 60,
                    branches: 39,
                    functions: 55
                }
            }
        },
        reporters: ['progress', 'kjhtml', 'sabarivka', 'coverage-istanbul'],
        coverageReporter: {
            reporters: [],
            include: [
                // Specify include pattern(s) first
                'src/**/*.(ts|js)',
                // Then specify "do not include" patterns (note `!` sign on the beginning of each statement)
                '!src/main.(ts|js)',
                '!src/**/*.spec.(ts|js)',
                '!src/**/*.module.(ts|js)',
                '!src/**/*.model.(ts|js)',
                '!src/**/*.providers.(ts|js)',
                '!src/**/environment*.(ts|js)'
            ]
        },`

**Comment by kopach** [comment]
Hi @cyfer1313. Karma works in that way, that if you want some karma-reporter to be disabled - you do not include it in the `reporters` list. `karma-sabarivka-reporter` doesn't interact directly with Angular. It even doesn't know whether Angular exists in your project. 

`karma-sabarivka-reporter` depends upon `karma-coverage-istanbul-reporter` or  `karma-coverage` plugins. Mean, that if you want to use `karma-sabarivka-reporter` - some of those plugins should be enabled.

From what I can see, `angular-cli` automatically adds/removes `coverage-istanbul` plugin based on `codeCoverage` property from  config. See here https://github.com/angular/angular-cli/blob/9d9d46bab3fcd64d4a2f61ff1eb832a8656cb194/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts#L76

So, what I would suggest you to do – is adding similar switch to your `karma.conf.js` file. Something like this:

```js
if(config.buildWebpack.options.codeCoverage) {
   reporters.push('sabarivka')
}
```
Please, let me know, if that helped

**Comment by kopach** [comment]
In older versions of angular-cli, I see they use something like this: https://github.com/angular/angular-cli-stress-test/blob/4c4df522fbbd0989068810c3d77dd0563f87b58b/karma.conf.js#L42
```js
    reporters: config.angularCli && config.angularCli.codeCoverage
              ? ['progress', 'coverage-istanbul']
              : ['progress', 'kjhtml'],
```

**Comment by cyfer1313** [comment]
Thanks. I’ll give that a shot.

**Comment by cyfer1313** [comment]
I’m in angular 10

**Comment by kopach** [comment]
Hi @cyfer1313, any updates on this?

**Comment by cyfer1313** [comment]
That worked for me.

-C
