### ISSUE TITLE
No mention of adding plugin entry in docs

### ISSUE THREAD

**Issue by johnthagen** [kopach/karma-sabarivka-reporter#24]
I needed to add to `karma.conf.js`:

```ts
    plugins: [
      ...
      require("karma-sabarivka-reporter"),
      ...
  ]
```

Or the tests would fail. Should this be added to the README?

**Comment by kopach** [comment]
HI @johnthagen. Thank you. I'll update documentation.

**Comment by kopach** [comment]
@johnthagen documentation updated. Thank you.

**Comment by johnthagen** [comment]
Thanks!
