### ISSUE TITLE
v3.1.1 breaks use with `karma-coverage`

### ISSUE THREAD

**Issue by Lalem001** [kopach/karma-sabarivka-reporter#50]
Karma's official [coverage reporter](https://www.npmjs.com/package/karma-coverage) was generating coverage reports just fine with v3.1.0. The subsequent release of v3.1.1 has stopped showing coverage for untested files.

Simple fix would add `'coverage'` to the list of permissible reporters.

```javascript
return !!reporters && (isIn(reporters, 'coverage') || isIn(reporters, 'coverage-istanbul'));
```

**Comment by kopach** [comment]
Hi @Lalem001. Thank you for your feedback. I haven't tested `karma-sabarivka-reporter` with karma-coverage before. Thank you for the comment - I'll definitely do that. Would you like to create PR yourself for this change as you have it done already? I'll accept it even without tests, I can update tests myself in separate PR.

**Comment by kopach** [comment]
@Lalem001, I've just encouraged strange issue while testing your feature. It looks like when `karma-coverage` reporter is used, order of reporters is important. 
When `sabarivka` is registered before `coverage` -> `karma-sabarivka-reporter` doesn't work (means, doesn't have influence of final code coverage). Is that behaviour also valid for your case?

**Comment by Lalem001** [comment]
My configuration has `sabarivka` before `coverage` as follows:

```javascript
reporters: ['dots', 'junit', 'sabarivka', 'coverage'],
```

This works for me, and I get the expected output. If I reverse the order then `sabarivka` does not influence the output. So yes order is important.

**Comment by kopach** [comment]
Could you, check, please, `sabarivka` after `coverage`? Just would like to confirm this. So, if this the only way - I'll add this to documentation (or even add some warning if used incorrectly)

**Comment by kopach** [comment]
@Lalem001, new version [v3.2.0](https://github.com/kopach/karma-sabarivka-reporter/releases/tag/v3.2.0) is released. Please, check it out.

**Comment by Lalem001** [comment]
Yes it works, thank you!
